name: jessies_cookbook
description: Jessie's first project with flutter, about the cookbook

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  transparent_image: ^2.0.1
  sqflite: ^2.0.0+4
  path: ^1.9.0
  shared_preferences: ^2.3.5
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true