name: jessies_cookbook
description: Jessie's first project with flutter, about the cookbook

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  transparent_image: ^2.0.1
  sqflite: ^2.0.0+4
  path: ^1.9.0
  shared_preferences: ^2.3.5
  path_provider: ^2.1.5
  http: ^1.3.0
  web_socket_channel: ^3.0.2
  google_fonts: ^5.0.0
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.2.0
  dio: ^5.0.0
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true